// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jhbi7rt9F-RuhF8hvoqAYt2LhaoKo7w',
    appId: '1:595987536473:web:286c48ceb675a636322f48',
    messagingSenderId: '595987536473',
    projectId: 'fir-demo-255e9',
    authDomain: 'fir-demo-255e9.firebaseapp.com',
    storageBucket: 'fir-demo-255e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_4fcHJ8cqbhguBWuv76MZPDffLAw1Zk',
    appId: '1:595987536473:android:5ba716c124b25d30322f48',
    messagingSenderId: '595987536473',
    projectId: 'fir-demo-255e9',
    storageBucket: 'fir-demo-255e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQFmnfkhJWimW6HbKDyj4OqWu0_Rc-7vo',
    appId: '1:595987536473:ios:7ef7bf3a882a6afb322f48',
    messagingSenderId: '595987536473',
    projectId: 'fir-demo-255e9',
    storageBucket: 'fir-demo-255e9.appspot.com',
    iosBundleId: 'com.example.firebaseBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQFmnfkhJWimW6HbKDyj4OqWu0_Rc-7vo',
    appId: '1:595987536473:ios:b278d17297e57cc0322f48',
    messagingSenderId: '595987536473',
    projectId: 'fir-demo-255e9',
    storageBucket: 'fir-demo-255e9.appspot.com',
    iosBundleId: 'com.example.firebaseBloc.RunnerTests',
  );
}
